apiVersion: batch/v1
kind: Job
metadata:
  generateName: presync-trident-protect-backup-
  annotations:
    argocd.argoproj.io/hook: PreSync
    argocd.argoproj.io/hook-delete-policy: BeforeHookCreation
spec:
  template:
    spec:
      containers:
      - name: alpine-tp
        image: alpine/k8s:1.31.5
        env:
          - name: APPNAME
            value: "ghost"
          - name: NAMESPACE
            value: "ghost"
          - name: APPVAULT
            value: "argocdtest"
          - name: TP_CLI_VERSION
            value: "24.10.1"
        command: ["/bin/sh"]
        args:
          - -c
          - >
            echo Environment variables: $APPNAME $NAMESPACE $APPVAULT $TP_CLI_VERSION &&
            echo curl -L -o tridentctl-protect https://github.com/NetApp/tridentctl-protect/releases/download/$TP_CLI_VERSION/tridentctl-protect-linux-amd64 &&
            echo chmod +x tridentctl-protect &&
            echo cp ./tridentctl-protect /usr/local/bin/ &&
            echo tridentctl-protect: backing up app $APPNAME &&
            echo tridentctl-protect create backup argo-presync-`date "+%Y%m%d%H%M%S"` --app $APPNAME --appvault $APPVAULT -n $NAMESPACE
      restartPolicy: Never
  backoffLimit: 1